// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default Firebase configuration options for your app.
///
/// This class provides Firebase configuration for the Robin Radio app.
/// The configuration should be generated using 'flutterfire configure'
/// to ensure proper platform-specific settings.
class DefaultFirebaseOptions {
  /// Returns the Firebase configuration for the current platform.
  ///
  /// This getter provides the appropriate FirebaseOptions based on the
  /// platform the app is running on. The configuration includes API keys,
  /// app IDs, and other necessary Firebase settings.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbLmYeHkIPOX2JELO7rqlKXmkZrfAsnM',
    appId: '1:275246812933:web:0490a71d657c7bf66c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
    authDomain: 'robin-radio.firebaseapp.com',
    measurementId: 'G-3FS1J0HFG5',
  );

  /// Firebase configuration for Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxzljYMisByRgddXKfHgIbbVoHtBxBFJg',
    appId: '1:275246812933:android:213c25ea2338e6176c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
  );

  /// Firebase configuration for iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxIDqjlG2N4pjQLFWUF4UgA30oFGksdjs',
    appId: '1:275246812933:ios:77e94c7ac20082596c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
    iosBundleId: 'com.tauristTechnologies.robinRadio',
  );

  /// Firebase configuration for macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxIDqjlG2N4pjQLFWUF4UgA30oFGksdjs',
    appId: '1:275246812933:ios:77e94c7ac20082596c316c',
    messagingSenderId: '275246812933',
    projectId: 'robin-radio',
    storageBucket: 'robin-radio.appspot.com',
    iosBundleId: 'com.tauristTechnologies.robinRadio',
  );
}
