// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default Firebase configuration options for your app.
///
/// This class provides Firebase configuration for the Robin Radio app.
/// The configuration should be generated using 'flutterfire configure'
/// to ensure proper platform-specific settings.
class DefaultFirebaseOptions {
  /// Returns the Firebase configuration for the current platform.
  ///
  /// This getter provides the appropriate FirebaseOptions based on the
  /// platform the app is running on. The configuration includes API keys,
  /// app IDs, and other necessary Firebase settings.
  static FirebaseOptions get currentPlatform =>
      // Replace these with your actual Firebase configuration values
      // You should run 'flutterfire configure' to generate this file properly
      const FirebaseOptions(
        apiKey: 'YOUR_API_KEY',
        appId: 'YOUR_APP_ID',
        messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
        projectId: 'YOUR_PROJECT_ID',
      );
}
